[server]
headless = false
port = 8501
enableCORS = false
enableXsrfProtection = true
enableWebsocketCompression = false
address = "0.0.0.0"
fileWatcherType = "poll"

[theme]
primaryColor = "#F63366"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

